jobs:
  CLAssistant:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_CLA_ASSISTANT
          }}
      if: (github.event.comment.body == 'recheck' || startsWith(github.event.comment.body,
        'I have read the CLA Document and I hereby sign the CLA')) || github.event_name
        == 'pull_request_target'
      name: CLA Assistant
      uses: cla-assistant/github-action@v2.1.2-beta
      with:
        allowlist: dependabot,bot*,github-actions
        branch: master
        path-to-document: https://github.com/apolloconfig/apollo-community/blob/master/CLA.md
        path-to-signatures: signatures/version1/cla.json
        remote-repository-name: apollo-community
name: CLA Assistant
on:
  repository_dispatch:
    types: trigger-ga___cla.yml
