jobs:
  commitlint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: wagoid/commitlint-github-action@v5
name: commit lint
on:
  repository_dispatch:
    types: trigger-ga___commit_lint.yml
