jobs:
  check:
    outputs:
      apollo-admin-tags: ${{ steps.check-tags.outputs.apollo-admin-tags }}
      apollo-config-tags: ${{ steps.check-tags.outputs.apollo-config-tags }}
      apollo-portal-tags: ${{ steps.check-tags.outputs.apollo-portal-tags }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: check-tags
      name: Check tags
      run: "if [[ ${{ github.event.inputs.version }} == *-SNAPSHOT ]]; then\n  echo\
        \ \"apollo-config-tags=apolloconfig/apollo-configservice:${{ github.event.inputs.version\
        \ }}\" >> $GITHUB_OUTPUT\n  echo \"apollo-admin-tags=apolloconfig/apollo-adminservice:${{\
        \ github.event.inputs.version }}\" >> $GITHUB_OUTPUT\n  echo \"apollo-portal-tags=apolloconfig/apollo-portal:${{\
        \ github.event.inputs.version }}\" >> $GITHUB_OUTPUT\nelse\n  echo \"apollo-config-tags=apolloconfig/apollo-configservice:${{\
        \ github.event.inputs.version }},apolloconfig/apollo-configservice:latest\"\
        \ >> $GITHUB_OUTPUT\n  echo \"apollo-admin-tags=apolloconfig/apollo-adminservice:${{\
        \ github.event.inputs.version }},apolloconfig/apollo-adminservice:latest\"\
        \ >> $GITHUB_OUTPUT\n  echo \"apollo-portal-tags=apolloconfig/apollo-portal:${{\
        \ github.event.inputs.version }},apolloconfig/apollo-portal:latest\" >> $GITHUB_OUTPUT\n\
        fi\n"
  publish:
    needs: check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      name: Build package
      run: ./scripts/build.sh
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Build and push apollo-configservice
      uses: docker/build-push-action@v3
      with:
        build-args: VERSION=${{ github.event.inputs.version }}
        context: ./apollo-configservice/target
        file: ./apollo-configservice/src/main/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ needs.check.outputs.apollo-config-tags }}
    - continue-on-error: true
      name: Build and push apollo-adminservice
      uses: docker/build-push-action@v3
      with:
        build-args: VERSION=${{ github.event.inputs.version }}
        context: ./apollo-adminservice/target
        file: ./apollo-adminservice/src/main/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ needs.check.outputs.apollo-admin-tags }}
    - continue-on-error: true
      name: Build and push apollo-portal
      uses: docker/build-push-action@v3
      with:
        build-args: VERSION=${{ github.event.inputs.version }}
        context: ./apollo-portal/target
        file: ./apollo-portal/src/main/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ needs.check.outputs.apollo-portal-tags }}
name: Publish Docker Image
on:
  repository_dispatch:
    types: trigger-ga___docker-publish.yml
