jobs:
  license:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Check License
      uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
name: license
on:
  repository_dispatch:
    types: trigger-ga___license.yml
